# Generated by Django 3.2 on 2021-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_image_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='test',
            field=models.CharField(default='Hello world', max_length=20),
        ),
    ]
