# Generated by Django 3.2 on 2021-04-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_image_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='test',
        ),
    ]
