# Generated by Django 3.2 on 2021-05-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Taken', 'Not Taken'), ('Taken', 'Taken'), ('Delivered', 'Delivered')], max_length=30, null=True),
        ),
    ]
