# Generated by Django 3.2 on 2021-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
